apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root_password
  MYSQL_DATABASE: demo_app
  MYSQL_USER: demo_user
  MYSQL_PASSWORD: demo_password
