apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1 # This will split 1 pod to one node, and 1 pod to another node
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      # nodeName: minikube-m04
      # topologySpreadConstraints:
      #   - maxSkew: 1
      #     topologyKey: kubernetes.io/instance-type
      #     whenUnsatisfiable: ScheduleAnyway  # Fixed: Changed 's' to capital 'S'
      #     labelSelector:
      #       matchLabels:
      #         app: frontend
      containers:
      - name: frontend
        image: frontend
        imagePullPolicy: Never
        # env:
        # - name: Name
        #   value: ashwani
        ports:
        - containerPort: 80